State.delete_all()
State.create(:name => 'Virginia', :abbreviation => 'VA', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'New York', :abbreviation => 'NY', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Massachusetts', :abbreviation => 'MA', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'New Jersey', :abbreviation => 'NJ', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Maryland', :abbreviation => 'MD', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Pennsylvania', :abbreviation => 'PA', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Delaware', :abbreviation => 'DE', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Washington, DC', :abbreviation => 'DC', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'West Virginia', :abbreviation => 'WV', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Alabama', :abbreviation => 'AL', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'Arkansas', :abbreviation => 'AR', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'Florida', :abbreviation => 'FL', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'North Carolina', :abbreviation => 'NC', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'American Samoa', :abbreviation => 'AS', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'Federated States of Micronesia', :abbreviation => 'FM', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'Puerto Rico', :abbreviation => 'PR', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'Georgia', :abbreviation => 'GA', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'Louisiana', :abbreviation => 'LA', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'Colorado', :abbreviation => 'CO', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Illinois', :abbreviation => 'IL', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Montana', :abbreviation => 'MT', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'New Mexico', :abbreviation => 'NM', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Ohio', :abbreviation => 'OH', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Oklahoma', :abbreviation => 'OK', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'South Dakota', :abbreviation => 'SD', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Texas', :abbreviation => 'TX', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Utah', :abbreviation => 'UT', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Wisconsin', :abbreviation => 'WI', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Wyoming', :abbreviation => 'WY', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Minnesota', :abbreviation => 'MN', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Kansas', :abbreviation => 'KS', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Alaska', :abbreviation => 'AK', :region_id => Region.find_by_name('Western Region').id)
State.create(:name => 'Arizona', :abbreviation => 'AZ', :region_id => Region.find_by_name('Western Region').id)
State.create(:name => 'California', :abbreviation => 'CA', :region_id => Region.find_by_name('Western Region').id)
State.create(:name => 'Nevada', :abbreviation => 'NV', :region_id => Region.find_by_name('Western Region').id)
State.create(:name => 'Washington', :abbreviation => 'WA', :region_id => Region.find_by_name('Western Region').id)
State.create(:name => 'Maine', :abbreviation => 'ME', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'New Hampshire', :abbreviation => 'NH', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Vermont', :abbreviation => 'VT', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Connecticut', :abbreviation => 'CT', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Rhode Island', :abbreviation => 'RI', :region_id => Region.find_by_name('NE Region').id)
State.create(:name => 'Michigan', :abbreviation => 'MI', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Indiana', :abbreviation => 'IN', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Kentucky', :abbreviation => 'KY', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Tennessee', :abbreviation => 'TN', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Mississippi', :abbreviation => 'MS', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'South Carolina', :abbreviation => 'SC', :region_id => Region.find_by_name('SE Region').id)
State.create(:name => 'Iowa', :abbreviation => 'IA', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Missouri', :abbreviation => 'MO', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'North Dakota', :abbreviation => 'ND', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Nebraska', :abbreviation => 'NE', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Idaho', :abbreviation => 'ID', :region_id => Region.find_by_name('Central Region').id)
State.create(:name => 'Oregon', :abbreviation => 'OR', :region_id => Region.find_by_name('Western Region').id)
State.create(:name => 'Hawaii', :abbreviation => 'HI', :region_id => Region.find_by_name('Western Region').id)
